package africa.makola;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "LocationsTable")
public class WeatherItem {

  public String locationName;

  public Double temperature;

  public Long timestamp;

  public Double longitude;

  public Double latitude;

  // private String id;

  @DynamoDBHashKey()
  public String getLocationName() {
    return locationName;
  }

  public void setLocationName(String locationName) {
    this.locationName = locationName;
  }

  @DynamoDBRangeKey
  public Double getTemperature() {
    return temperature;
  }

  public void setTemperature(Double temperature) {
    this.temperature = temperature;
  }

  @DynamoDBAttribute
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  @DynamoDBAttribute
  public Double getLongitude() {
    return longitude;
  }

  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }

  @DynamoDBAttribute
  public Double getLatitude() {
    return latitude;
  }

  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }

  //  @DynamoDBHashKey()
  //  @DynamoDBAutoGeneratedKey
  //  public String getId() {
  //    return id;
  //  }
  //
  //  public void setId(String id) {
  //    this.id = id;
  //  }

  public WeatherItem() {}

  public WeatherItem(
      final String locationName,
      final Double temperature,
      final Long timestamp,
      final Double longitude,
      final Double latitude) {

    this.locationName = locationName;
    this.temperature = temperature;
    this.timestamp = timestamp;
    this.longitude = longitude;
    this.latitude = latitude;
  }

  @Override
  public String toString() {
    return "WeatherItem{"
        + "locationName='"
        + locationName
        + '\''
        + ", temperature="
        + temperature
        + ", timestamp="
        + timestamp
        + ", longitude="
        + longitude
        + ", latitude="
        + latitude
        + '}';
  }
}
